Vagrant.configure(2) do |config|
  # образ системы Ubuntu 18/04 LTS (Bionic Beaver)
  config.vm.box = "ubuntu/bionic64"
  # не проверять репозиторий на наличие обновлений
  config.vm.box_check_update = false
  # отменить создание ssh-ключа
  # config.ssh.insert_key = false

  # ПЕРВАЯ ВИРТУАЛЬНАЯ МАШИНА
  config.vm.define "ab-haproxy" do |subconfig|
    # имя виртуальной машины
    subconfig.vm.provider "virtualbox" do |vb|
      vb.name = "ab-haproxy"
      vb.memory = "512"
      vb.cpus = "1"
    end
    # hostname виртуальной машины
    subconfig.vm.hostname = "ab-haproxy"
    # настройки сети
    subconfig.vm.network "private_network", ip: "192.168.53.11"
    # установка пакетов
    # subconfig.vm.provision "apache", type: "shell", inline: "apt-get install -y apache2"
  end

  # ВТОРАЯ ВИРТУАЛЬНАЯ МАШИНА
  config.vm.define "ab-logstash" do |subconfig|
    # имя виртуальной машины
    subconfig.vm.provider "virtualbox" do |vb|
      vb.name = "ab-logstash"
      vb.memory = "512"
      vb.cpus = "1"
    end
    # hostname виртуальной машины
    subconfig.vm.hostname = "ab-logstash"
    # настройки сети
    subconfig.vm.network "private_network", ip: "192.168.53.12"
    # установка пакетов
    # subconfig.vm.provision "mysql", type: "shell", inline: "apt-get install -y mysql-server"
  end

  # ТРЕТЬЯ ВИРТУАЛЬНАЯ МАШИНА
  config.vm.define "ab-webui" do |subconfig|
    # имя виртуальной машины
    subconfig.vm.provider "virtualbox" do |vb|
      vb.name = "ab-webui"
      vb.memory = "512"
      vb.cpus = "1"
    end
    # hostname виртуальной машины
    subconfig.vm.hostname = "ab-webui"
    # настройки сети
    subconfig.vm.network "private_network", ip: "192.168.53.13"
    # установка пакетов
    # subconfig.vm.provision "mysql", type: "shell", inline: "apt-get install -y mysql-server"
  end

  # обновление системы (для первой и второй)
  # config.vm.provision "update", type: "shell", inline: "apt-get update && apt-get upgrade -y"
end
