apiVersion: apps/v1
kind: Deployment
metadata:
  name: itr-test-depolyment
  labels:
    app: my-k8s-application
spec:
  selector:
    matchLabels:
      project: itr-test
  template:
    metadata:
      labels:
        project: itr-test
    spec:
      containers:
        - name : itr-test-app
          image : crccheck/hello-world:latest
          ports:
            - containerPort: 80
